// src/themes.js
// Semua tema menggunakan efek "Clear Glass" agar background slideshow tetap terlihat

export const themes = {
  gelap: {
    name: 'Gelap',
    bgBase: 'bg-[#1a1412]',
    bgPanel: 'bg-black/30 backdrop-blur-2xl',
    textMain: 'text-amber-50',
    textMuted: 'text-amber-500/70',
    accent: 'text-red-400',
    border: 'border-white/10',
    buttonBg: 'bg-red-800/80 hover:bg-red-700',
    buttonText: 'text-amber-50',
    overlayBg: 'bg-black/55',
  },
  terang: {
    name: 'Terang',
    bgBase: 'bg-slate-200',
    bgPanel: 'bg-white/40 backdrop-blur-2xl',
    textMain: 'text-slate-800',
    textMuted: 'text-slate-500',
    accent: 'text-blue-600',
    border: 'border-slate-300/50',
    buttonBg: 'bg-blue-600 hover:bg-blue-700',
    buttonText: 'text-white',
    overlayBg: 'bg-white/55',
  },
  neon: {
    name: 'Neon Night',
    bgBase: 'bg-gray-950',
    bgPanel: 'bg-black/35 backdrop-blur-2xl',
    textMain: 'text-cyan-300',
    textMuted: 'text-fuchsia-400/70',
    accent: 'text-fuchsia-400',
    border: 'border-cyan-500/25',
    buttonBg: 'bg-fuchsia-600/90 hover:bg-fuchsia-500',
    buttonText: 'text-white',
    overlayBg: 'bg-gray-950/60',
  },
  retro: {
    name: 'Retro 80s',
    bgBase: 'bg-[#F4ECD8]',
    bgPanel: 'bg-[#E8DAB2]/35 backdrop-blur-2xl',
    textMain: 'text-[#4A3B32]',
    textMuted: 'text-[#8A7968]',
    accent: 'text-[#D95D39]',
    border: 'border-[#C0A98E]/40',
    buttonBg: 'bg-[#D95D39] hover:bg-[#C24D2C]',
    buttonText: 'text-[#F4ECD8]',
    overlayBg: 'bg-[#F4ECD8]/50',
  },
  cyberpunk: {
    name: 'Cyberpunk',
    bgBase: 'bg-gray-950',
    bgPanel: 'bg-gray-900/35 backdrop-blur-2xl',
    textMain: 'text-yellow-400',
    textMuted: 'text-cyan-400/80',
    accent: 'text-cyan-400',
    border: 'border-cyan-400/30',
    buttonBg: 'bg-cyan-400 hover:bg-cyan-300',
    buttonText: 'text-gray-900 font-black',
    overlayBg: 'bg-gray-950/65',
  },
};
